apiVersion: v1
kind: Pod
metadata:
  name: newpod
  labels:
    app: newpod
spec:
   containers:
    - name: newcontain
      image: anilkumblepuli/java2:tagVersion
      ports:
       - name: vproapp-port1
         containerPort: 8080
