apiVersion: v1
kind: Pod
metadata:
  name: vproapp
  labels:
    app: vproapp
spec:
   containers:
    - name: vproapp
      image: anilkumblepuli/java2:tagVersion
      ports:
       - name: vproapp-port
         containerPort: 8080
