apiVersion: v1
kind: Service
metadata:
   name: vproapp-servic
spec:
   ports:
   - port: 30001
     nodePort: 30001
     targetPort: vproapp-port1
     protocol: TCP
  selector:
     app: newpod
  type: NodePort
